import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainWithSnap from "./MainWithSnap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-background text-foreground">
          <header className="border-b border-zinc-200 bg-background/80 backdrop-blur dark:border-zinc-800">
            <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-4">
              <span className="text-sm font-medium text-zinc-700 dark:text-zinc-300">
                HuaXin Zhang   |   张铧心
              </span>
              <nav className="flex gap-4 text-sm text-zinc-600 dark:text-zinc-300">
                <Link
                  href="/"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  Home
                </Link>
                <Link
                  href="/about"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  About me
                </Link>
                <Link
                  href="/cv"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  Curriculum Vitae
                </Link>
                <Link
                  href="/work"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  Works
                </Link>
                <Link
                  href="/blog"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  Blog
                </Link>
                <Link
                  href="/music"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  Music
                </Link>
                <Link
                  href="/photographs"
                  className="transition hover:text-zinc-900 hover:underline dark:hover:text-zinc-50"
                >
                  Photographs
                </Link>
              </nav>
            </div>
          </header>
          <MainWithSnap>{children}</MainWithSnap>
        </div>
      </body>
    </html>
  );
}
